version: "3.9"
services:

#admin

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${NAME}
      MYSQL_USER: ${NAME}
      MYSQL_PASSWORD: ${PASSWD}
      MYSQL_ROOT_PASSWORD: ${PASSWD}
    volumes:
      - /home/nas/wp_danika/db:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    links:
          - mariadb
    expose:
      - "PORT"
    ports:
      - "PORT:80"
    environment:
      - PMA_HOST=${DBNAME}
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${PASSWD}
      - PMA_ARBITRARY=1
    volumes:
      - /home/nas/wp_danika/phpmyadmin:/etc/phpmyadmin
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - PORT:81 # danci http
      - PORT:82 # hetti http
    volumes:
      - /home/nas/wp_danika/nginx/conf:/etc/nginx/conf.d
    networks:
      - app-network

#szekedani.ddns.net

  wordpress_danci:
    depends_on: 
          - mariadb
          - phpmyadmin
          - nginx
    container_name: wordpress_danci
    image: wordpress:php8.1-apache
    restart: always
    ports:
      - PORT:80
    environment:
      WORDPRESS_DB_HOST: ${DBNAME}
      WORDPRESS_DB_USER: ${NAME}
      WORDPRESS_DB_PASSWORD: ${PASSWD}
      WORDPRESS_DB_NAME: ${NAME}
    volumes:
      - /home/nas/wp_danika/wordpress:/var/www/html
    networks:
      - app-network

#tamashenriett.ddns.net

  wordpress_hetti:
    depends_on: 
          - mariadb
          - phpmyadmin
          - nginx
    container_name: wordpress_hetti
    image: wordpress:php8.1-apache
    restart: always
    ports:
      - PORT:80
    environment:
      WORDPRESS_DB_HOST: ${DBNAME}
      WORDPRESS_DB_USER: ${NAME2}
      WORDPRESS_DB_PASSWORD: ${PASSWD2}
      WORDPRESS_DB_NAME: ${NAME2}
    volumes:
      - /home/nas/wp_hetti/wordpress:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


##ssl


#      - /home/nas/wp_danika/certbot/conf:/etc/nginx/ssl
#      - /home/nas/wp_danika/certbot/data:/var/www/html
#  certbot:
#    container_name: certbot
#    image: certbot/certbot:latest
#    command: certonly --webroot --webroot-path=/var/www/html --email address@gmail.com --agree-tos --no-eff-email -d domain.com -d www.domain.com
#    volumes:
#      - /home/nas/wp_danika/certbot/conf:/etc/letsencrypt
#      - /home/nas/wp_danika/certbot/logs:/var/log/letsencrypt
#      - /home/nas/wp_danika/certbot/data:/var/www/html
